// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gridLikelihood
NumericVector gridLikelihood(NumericVector& x, const NumericVector& row, const NumericVector& gridX);
RcppExport SEXP _EmpiricalCalibration_gridLikelihood(SEXP xSEXP, SEXP rowSEXP, SEXP gridXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type row(rowSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type gridX(gridXSEXP);
    rcpp_result_gen = Rcpp::wrap(gridLikelihood(x, row, gridX));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EmpiricalCalibration_gridLikelihood", (DL_FUNC) &_EmpiricalCalibration_gridLikelihood, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_EmpiricalCalibration(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
