# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gridLlApproximation <- function(x, parameters) {
    .Call('_EmpiricalCalibration_gridLlApproximation', PACKAGE = 'EmpiricalCalibration', x, parameters)
}

samplePoissonMaxLrr <- function(groupSizes, minimumEvents, sampleSize, nullMean, nullSd) {
    .Call('_EmpiricalCalibration_samplePoissonMaxLrr', PACKAGE = 'EmpiricalCalibration', groupSizes, minimumEvents, sampleSize, nullMean, nullSd)
}

sampleBinomialMaxLrr <- function(groupSizes, p, minimumEvents, sampleSize, nullMean, nullSd) {
    .Call('_EmpiricalCalibration_sampleBinomialMaxLrr', PACKAGE = 'EmpiricalCalibration', groupSizes, p, minimumEvents, sampleSize, nullMean, nullSd)
}

samplePoissonRegressionMaxLrr <- function(groupSizes, z, minimumEvents, sampleSize) {
    .Call('_EmpiricalCalibration_samplePoissonRegressionMaxLrr', PACKAGE = 'EmpiricalCalibration', groupSizes, z, minimumEvents, sampleSize)
}

logLikelihoodNull <- function(theta, logRr, seLogRr) {
    .Call('_EmpiricalCalibration_logLikelihoodNull', PACKAGE = 'EmpiricalCalibration', theta, logRr, seLogRr)
}

